import { Link } from "wouter";
import { ArrowDownRight, ArrowUpRight, Check, Droplets, FileCheck2, MapPin, ShieldCheck, Sparkles, Wrench, Zap } from "lucide-react";
import { EmergencyBar, Footer, FaqItem, LeadForm, SectionEyebrow, SiteHeader } from "@/components/SiteChrome";

const services = [
  ["Fuite d'eau", "Une fuite visible ou un dégât des eaux ? Commencez par limiter les dégâts.", "/fuite-eau-marseille", Droplets, "peach"],
  ["Débouchage", "WC, évier, douche ou canalisation : décrivez le symptôme avant d'agir.", "/debouchage-marseille", Wrench, "mint"],
  ["Urgence plomberie", "Un problème qui ne peut pas attendre ? Faites une demande contextualisée.", "/urgence-plomberie-marseille", Zap, "blue"],
  ["Chauffe-eau", "Panne, fuite ou remplacement : préparez les bonnes informations.", "/chauffe-eau-marseille", Sparkles, "yellow"],
  ["Recherche de fuite", "Une trace d'humidité sans origine visible mérite un diagnostic ciblé.", "/recherche-fuite-marseille", MapPin, "lavender"],
  ["Installation", "Salle de bains, robinetterie ou réseau : demandez un devis planifié.", "/installation-plomberie-marseille", FileCheck2, "grey"],
] as const;

const areas = ["Marseille 1er", "Marseille 2e", "Marseille 4e", "Marseille 5e", "Marseille 6e", "Marseille 7e", "Marseille 8e", "Marseille 9e", "Marseille 10e", "Marseille 11e", "Marseille 12e", "Marseille 13e", "Marseille 14e", "Marseille 15e", "Marseille 16e", "Aubagne", "Allauch", "Cassis", "Plan-de-Cuques", "La Penne-sur-Huveaune"];

const insights = [
  ["Urgence plomberie", "Les premiers gestes en cas de fuite d'eau à Marseille", "urgence-plomberie-marseille", "4 min"],
  ["Dépannage", "Combien coûte un plombier à Marseille ?", "plombier-pas-cher-marseille", "5 min"],
  ["Canalisations", "Débouchage : quoi vérifier avant de demander de l'aide", "debouchage-marseille", "3 min"],
];

export default function Home() {
  return <div className="site-shell"><EmergencyBar /><SiteHeader /><main>
    <section className="plumbee-hero"><div className="container plumbee-hero-grid"><div className="hero-copy"><div className="hero-kicker"><span className="status-dot" /> Plomberie locale · Marseille & alentours</div><h1>La plomberie,<br /><span>sans prise de tête.</span></h1><p>De la fuite d'eau à l'installation complète, décrivez votre besoin. Vous recevez une première orientation claire, avec les bons repères pour avancer sereinement.</p><div className="hero-actions"><a href="#contact" className="button button-orange">Décrire mon problème <ArrowUpRight size={16} /></a><a className="text-link" href="#method">Voir comment ça marche <ArrowDownRight size={16} /></a></div><div className="hero-proof"><span><Check size={14} /> Demande en ligne</span><span><Check size={14} /> Marseille local</span><span><Check size={14} /> Sans engagement</span></div></div><div className="hero-visual"><div className="hero-orbit orbit-one" /><div className="hero-orbit orbit-two" /><div className="hero-blob"><Droplets size={90} strokeWidth={1.1} /></div><div className="floating-card floating-top"><span className="floating-icon green"><Check size={15} /></span><div><strong>Demande claire</strong><small>Les bonnes infos dès le départ</small></div></div><div className="floating-card floating-bottom"><span className="floating-icon orange"><MapPin size={15} /></span><div><strong>20 zones couvertes</strong><small>Marseille & périphérie</small></div></div><span className="visual-scribble">simple & local</span></div></div></section>

    <section className="trust-row"><div className="container trust-row-inner"><span className="trust-intro">Pourquoi commencer ici ?</span><div><ShieldCheck size={17} /><strong>Des informations utiles</strong><small>avant de faire intervenir</small></div><div><Sparkles size={17} /><strong>Un parcours simple</strong><small>urgence ou projet</small></div><div><MapPin size={17} /><strong>Une recherche locale</strong><small>par quartier et commune</small></div><a href="#contact" className="trust-link">Faire une demande <ArrowUpRight size={14} /></a></div></section>

    <section className="section intro-section" id="services"><div className="container"><div className="section-intro split-intro"><div><SectionEyebrow>Comment on peut vous aider</SectionEyebrow><h2>Le bon point de départ,<br /><em>quel que soit le problème.</em></h2></div><p>Vous recherchez un plombier à Marseille, un dépannage, un devis ou simplement les premiers gestes ? Choisissez la situation qui ressemble le plus à la vôtre.</p></div><div className="service-grid-new">{services.map(([title, text, href, Icon, color]) => <Link href={href} className={`service-tile ${color}`} key={title}><span className="tile-icon"><Icon size={23} /></span><span className="tile-arrow"><ArrowUpRight size={17} /></span><h3>{title}</h3><p>{text}</p><span className="tile-link">En savoir plus</span></Link>)}</div></div></section>

    <section className="method-section" id="method"><div className="container method-grid"><div className="method-statement"><SectionEyebrow>Notre méthode</SectionEyebrow><h2>Pas de jargon.<br /><em>Pas de zone grise.</em></h2><p>Quand un problème de plomberie arrive, le plus utile est souvent de savoir quoi décrire et quelle est la prochaine étape. Le site est organisé pour ça.</p><a className="button button-dark" href="#contact">Commencer une demande <ArrowUpRight size={16} /></a></div><div className="method-steps"><div className="method-step"><span>01</span><div><h3>Vous racontez</h3><p>Quelques mots, une photo si vous en avez une, votre arrondissement et le niveau d'urgence.</p></div></div><div className="method-step"><span>02</span><div><h3>On précise</h3><p>Les informations utiles sont regroupées pour éviter les allers-retours inutiles.</p></div></div><div className="method-step"><span>03</span><div><h3>Vous avancez</h3><p>Vous recevez une orientation vers une urgence, un diagnostic ou un devis planifié.</p></div></div></div></div></section>

    <section className="section local-section" id="zones"><div className="container"><div className="section-intro split-intro"><div><SectionEyebrow>Marseille et autour</SectionEyebrow><h2>Votre quartier,<br /><em>notre point de départ.</em></h2></div><p>La recherche « plombier Marseille » devient plus utile quand elle précise une zone. Explorez les arrondissements, Aubagne, Allauch, Cassis et les communes voisines.</p></div><div className="area-cloud">{areas.map((area) => { const postal = area.match(/\d+/)?.[0]; const href = postal ? `/plombier-marseille-130${postal.padStart(2, "0")}` : `/zones/${area.toLowerCase().replaceAll(" ", "-")}`; return <Link href={href} key={area}><MapPin size={14} /> {area}<ArrowUpRight size={13} /></Link>; })}</div><div className="local-banner"><div><span className="banner-mark"><MapPin size={18} /></span><div><strong>Vous ne trouvez pas votre zone ?</strong><small>Les Bouches-du-Rhône ne s'arrêtent pas à une liste.</small></div></div><a href="#contact">Décrire mon adresse <ArrowUpRight size={15} /></a></div></div></section>

    <section className="section insights-section" id="insights"><div className="container"><div className="section-intro split-intro"><div><SectionEyebrow>Le carnet plomberie</SectionEyebrow><h2>Comprendre avant<br /><em>d'intervenir.</em></h2></div><p>Des réponses concrètes sur les fuites, les bouchons et les travaux de plomberie à Marseille. Lisez, puis demandez un avis adapté à votre cas.</p></div><div className="insights-grid">{insights.map(([category, title, slug, time], index) => <Link href={`/${slug}`} className="insight-card" key={slug}><div className={`insight-image insight-${index}`}><span>{index === 0 ? <Droplets size={39} /> : index === 1 ? <Sparkles size={39} /> : <Wrench size={39} />}</span></div><div className="insight-info"><span className="insight-category">{category}</span><h3>{title}</h3><div><span>{time} de lecture</span><ArrowUpRight size={16} /></div></div></Link>)}</div></div></section>

    <section className="section contact-section-new" id="contact"><div className="container contact-grid-new"><div className="contact-copy-new"><SectionEyebrow>Parlons de votre problème</SectionEyebrow><h2>La première étape,<br /><em>c'est de décrire.</em></h2><p>Pas de numéro à chercher, pas de parcours compliqué. Laissez les informations utiles et revenez à l'essentiel.</p><div className="contact-list"><span><Check size={16} /> Fuite d'eau ou dégât des eaux</span><span><Check size={16} /> WC, évier ou canalisation bouchée</span><span><Check size={16} /> Chauffe-eau, robinetterie ou rénovation</span></div></div><LeadForm /></div></section>

    <section className="section faq-section" id="faq"><div className="container faq-grid"><div><SectionEyebrow>Questions fréquentes</SectionEyebrow><h2>Les réponses<br /><em>sans détour.</em></h2><p>Les questions utiles quand on cherche un plombier à Marseille, une urgence ou un devis pour un chantier.</p></div><div className="faq-list"><FaqItem question="Que faire en cas de fuite d'eau à Marseille ?" answer="Coupez l'arrivée d'eau si vous pouvez le faire sans risque, protégez les zones sensibles et notez l'origine supposée de la fuite. En cas d'eau proche d'une installation électrique, éloignez-vous et contactez les services compétents." /><FaqItem question="Comment demander un plombier pas cher à Marseille ?" answer="Décrivez précisément le problème et demandez ce qui est compris dans le déplacement, le diagnostic, la main-d'œuvre et les pièces. Une demande claire est plus facile à comparer." /><FaqItem question="Couvrez-vous les arrondissements de Marseille ?" answer="Le cocon couvre les 1er à 16e arrondissements, ainsi qu'Aubagne, Allauch, Plan-de-Cuques, Cassis et plusieurs communes proches. Indiquez votre zone dans le formulaire." /><FaqItem question="Puis-je demander un devis pour une rénovation ?" answer="Oui. Pour une salle de bains, une robinetterie, un WC, une évacuation ou un chauffe-eau, ajoutez des photos, les dimensions et votre calendrier souhaité." /></div></div></section>
  </main><Footer /></div>;
}
