export type SeoPage = {
  slug: string;
  keyword: string;
  title: string;
  area: string;
  intro: string;
  body: string[];
  questions: [string, string][];
  related: string[];
};

const baseQuestions: [string, string][] = [
  ["Comment choisir un plombier à Marseille ?", "Commencez par décrire la situation, l'arrondissement et le niveau d'urgence. Demandez ensuite ce qui est inclus dans le déplacement, le diagnostic et la main-d'œuvre avant toute intervention."],
  ["Combien coûte un plombier à Marseille ?", "Le prix varie selon le dépannage, l'accès, l'horaire et les pièces. Une demande précise permet d'obtenir une orientation et une estimation plus cohérentes."],
  ["Intervenez-vous dans mon arrondissement ?", "Le cocon couvre Marseille intra-muros du 1er au 16e arrondissement, ainsi que plusieurs communes proches. Indiquez votre zone dans le formulaire pour vérifier la disponibilité."],
];

const servicePages: SeoPage[] = [
  { slug: "plombier-marseille", keyword: "plombier Marseille", title: "Plombier Marseille : trouvez le bon interlocuteur", area: "Marseille et proche périphérie", intro: "Vous cherchez un plombier à Marseille pour une fuite, un débouchage, un chauffe-eau ou une rénovation ? Décrivez votre besoin et recevez une orientation claire, sans perdre de temps.", body: ["Plombier Marseille est la recherche de départ quand un problème de plomberie ne peut pas attendre. Un dégât des eaux, une canalisation bouchée ou une panne de chauffe-eau ne se traite pas de la même façon : le formulaire aide à préciser le bon besoin dès le premier échange.", "Cette page Plombier Marseille rassemble les services les plus demandés à Marseille, les arrondissements couverts et les premières informations à vérifier avant le déplacement. Vous pouvez demander une mise en relation pour une urgence plomberie Marseille comme pour un devis de rénovation."], questions: baseQuestions, related: ["plombier-a-marseille", "urgence-plomberie-marseille", "plombier-marseille-13008"] },
  { slug: "plombier-a-marseille", keyword: "plombier à Marseille", title: "Plombier à Marseille : demande locale et rapide", area: "Tous les arrondissements de Marseille", intro: "Besoin d'un plombier à Marseille ? Que le problème concerne votre appartement, votre maison, un commerce ou une copropriété, commencez par décrire ce qui se passe.", body: ["La requête plombier à Marseille peut désigner un dépannage urgent ou un chantier planifié. Une fuite sous évier demande une réponse différente d'une salle de bains à refaire ou d'un chauffe-eau à remplacer.", "Pour un plombier à Marseille, les détails utiles sont simples : l'adresse ou l'arrondissement, le symptôme, l'accès à l'eau et l'éventuelle urgence. Ces éléments permettent d'éviter une demande trop vague et d'obtenir une orientation plus pertinente."], questions: baseQuestions, related: ["plombier-marseille", "plombier-sur-marseille", "plombier-pas-cher-marseille"] },
  { slug: "plombier-sur-marseille", keyword: "plombier sur Marseille", title: "Plombier sur Marseille : urgence ou devis", area: "Marseille intra-muros", intro: "Vous recherchez un plombier sur Marseille ? Indiquez votre arrondissement et la nature du problème pour savoir quelle solution envisager.", body: ["Un plombier sur Marseille peut être sollicité pour un WC bouché, une fuite d'eau, un ballon d'eau chaude, une canalisation ou un projet de plomberie. Le plus utile est de transmettre une description courte et une photo si vous en avez une.", "Le site couvre les recherches locales plombier sur Marseille et les variantes par arrondissement. Chaque zone possède ses propres contraintes d'accès, de stationnement et de copropriété : précisez-les dès le départ."], questions: baseQuestions, related: ["plombier-marseille", "plombier-a-marseille", "urgence-plomberie-marseille"] },
  { slug: "plombier-pas-cher-marseille", keyword: "plombier pas cher Marseille", title: "Plombier pas cher à Marseille : comparer sans mauvaise surprise", area: "Marseille et Bouches-du-Rhône", intro: "Vous cherchez un plombier pas cher à Marseille ? Comparez surtout le périmètre de l'intervention, le déplacement et le prix annoncé avant de commencer.", body: ["Chercher un plombier pas cher à Marseille ne signifie pas choisir au hasard. Un tarif trop bas peut exclure le déplacement, le diagnostic, les pièces ou la majoration horaire. Demandez toujours une estimation détaillée avant de valider.", "Pour réduire le coût, préparez les informations utiles, coupez l'eau si possible et distinguez une urgence d'un devis planifié. Une demande claire aide à recevoir une proposition adaptée à la situation réelle."], questions: [["Comment obtenir un tarif de plombier pas cher à Marseille ?", "Décrivez précisément la panne, envoyez des photos si possible et demandez ce qui est compris avant le déplacement. La comparaison est plus fiable quand le périmètre est le même."], ...baseQuestions.slice(1)], related: ["plombier-marseille", "urgence-plomberie-marseille", "debouchage-marseille"] },
  { slug: "urgence-plomberie-marseille", keyword: "urgence plomberie Marseille", title: "Urgence plomberie Marseille : les premiers bons réflexes", area: "Marseille 1er à 16e", intro: "Fuite qui coule, WC qui déborde, canalisation qui refoule ou ballon qui fuit : une urgence plomberie à Marseille se décrit en quelques mots pour être orientée rapidement.", body: ["En cas d'urgence plomberie Marseille, coupez l'arrivée d'eau si vous pouvez le faire sans risque, éloignez les objets sensibles et notez l'origine visible de la fuite. Si l'électricité est exposée à l'eau, ne touchez pas à l'installation et mettez-vous en sécurité.", "La page urgence plomberie Marseille est conçue pour les situations où le temps compte. Indiquez l'arrondissement, le type de logement et si l'eau continue de couler : ce sont les informations les plus utiles pour la suite."], questions: [["Que faire avant l'arrivée d'un plombier en urgence ?", "Coupez l'eau, protégez les meubles, prenez des photos et ne démontez pas une installation si vous n'êtes pas sûr. En cas de risque électrique, éloignez-vous et contactez les services compétents."], ...baseQuestions.slice(1)], related: ["fuite-eau-marseille", "debouchage-marseille", "plombier-marseille-13008"] },
  { slug: "fuite-eau-marseille", keyword: "fuite d'eau Marseille", title: "Fuite d'eau à Marseille : identifier et limiter les dégâts", area: "Marseille et alentours", intro: "Une fuite d'eau à Marseille peut venir d'un siphon, d'un raccord, d'un flexible, d'un chauffe-eau ou d'une canalisation. Décrivez ce que vous voyez pour être orienté.", body: ["Pour une fuite d'eau Marseille, la priorité est de limiter le débit et de protéger les surfaces. Une photo de la zone humide, du raccord ou du compteur peut aider à distinguer une fuite visible d'une recherche plus approfondie.", "Une fuite d'eau à Marseille dans une copropriété doit aussi être signalée au voisin ou au syndic lorsque cela est nécessaire. Gardez les factures et les photos si un dossier d'assurance doit être constitué."], questions: [["Comment trouver l'origine d'une fuite d'eau ?", "Commencez par observer les raccords, les flexibles, le siphon et le compteur. Si l'humidité apparaît loin de la canalisation visible, une recherche de fuite peut être nécessaire."], ...baseQuestions.slice(1)], related: ["urgence-plomberie-marseille", "recherche-fuite-marseille", "plombier-marseille-13005"] },
  { slug: "debouchage-marseille", keyword: "débouchage Marseille", title: "Débouchage Marseille : WC, évier et canalisation", area: "Marseille intra-muros et périphérie", intro: "WC bouché, évier qui refoule, douche qui s'évacue mal : le débouchage à Marseille commence par identifier le type de bouchon et son emplacement.", body: ["La recherche débouchage Marseille couvre les WC, lavabos, éviers, douches et canalisations. Un simple ralentissement n'a pas la même cause qu'un refoulement ou qu'un bouchon récurrent dans une colonne commune.", "Évitez d'accumuler les produits chimiques lorsque l'origine n'est pas connue. Notez les appareils concernés, la vitesse d'écoulement et l'apparition éventuelle de mauvaises odeurs : ces indices sont utiles au diagnostic."], questions: [["Combien coûte un débouchage à Marseille ?", "Le prix dépend de l'accès, de la profondeur du bouchon et de l'outil nécessaire. Demandez si le déplacement, le diagnostic et le nettoyage sont inclus."], ...baseQuestions.slice(1)], related: ["urgence-plomberie-marseille", "plombier-pas-cher-marseille", "plombier-marseille-13001"] },
  { slug: "chauffe-eau-marseille", keyword: "chauffe-eau Marseille", title: "Chauffe-eau à Marseille : panne, fuite et remplacement", area: "Marseille et communes voisines", intro: "Plus d'eau chaude, ballon qui fuit ou groupe de sécurité qui goutte : un problème de chauffe-eau à Marseille mérite une description précise avant l'intervention.", body: ["Pour un chauffe-eau Marseille, précisez s'il s'agit d'un ballon électrique, d'un chauffe-eau gaz ou d'un appareil thermodynamique. La marque, l'âge, le volume et le symptôme peuvent faire gagner du temps.", "Un chauffe-eau qui fuit par la cuve, un groupe de sécurité qui goutte ou un appareil qui ne chauffe plus ne se remplace pas systématiquement. Une demande de diagnostic permet de comparer réparation, entretien et remplacement."], questions: [["Pourquoi mon chauffe-eau ne chauffe plus ?", "Les causes possibles incluent l'alimentation, le thermostat, la résistance, le contacteur ou un problème de sécurité. Ne démontez pas l'appareil sans couper les énergies concernées."], ...baseQuestions.slice(1)], related: ["fuite-eau-marseille", "plombier-marseille", "plomberie-marseille"] },
  { slug: "recherche-fuite-marseille", keyword: "recherche de fuite Marseille", title: "Recherche de fuite à Marseille : visible ou invisible", area: "Appartement, maison et copropriété", intro: "Trace d'humidité, consommation inhabituelle ou auréole au plafond : la recherche de fuite à Marseille permet de distinguer le symptôme de la cause.", body: ["Une recherche de fuite Marseille peut concerner une canalisation encastrée, une évacuation, une arrivée d'eau ou une infiltration. Les photos, la date d'apparition et la localisation des traces sont utiles pour préparer le diagnostic.", "Lorsqu'un voisin ou une assurance est concerné, demandez un compte-rendu précis de l'origine et des réparations. Cela facilite la coordination entre occupant, propriétaire, syndic et professionnel."], questions: [["Une recherche de fuite est-elle toujours destructive ?", "Non. Selon la situation, des méthodes ciblées peuvent limiter les ouvertures. Le professionnel choisit l'approche après observation des symptômes et du réseau."], ...baseQuestions.slice(1)], related: ["fuite-eau-marseille", "urgence-plomberie-marseille", "plombier-a-marseille"] },
  { slug: "plomberie-marseille", keyword: "plomberie Marseille", title: "Plomberie Marseille : dépannage, entretien et installation", area: "Bouches-du-Rhône", intro: "La plomberie à Marseille couvre les urgences, l'entretien, les remplacements d'équipements et les travaux de salle de bains. Décrivez votre projet pour recevoir une première orientation.", body: ["La recherche plomberie Marseille est plus large que la seule urgence. Elle peut concerner une rénovation de salle de bains, une robinetterie, une alimentation, une évacuation, un chauffe-eau ou l'entretien d'une installation.", "Pour une plomberie Marseille planifiée, ajoutez les dimensions, quelques photos, l'état actuel de l'installation et votre calendrier souhaité. Un projet bien documenté facilite l'établissement d'un devis comparable."], questions: baseQuestions, related: ["installation-plomberie-marseille", "plombier-marseille", "chauffe-eau-marseille"] },
  { slug: "installation-plomberie-marseille", keyword: "installation plomberie Marseille", title: "Installation plomberie Marseille : des travaux bien cadrés", area: "Maison, appartement et local professionnel", intro: "Création de salle de bains, installation de WC, robinetterie, alimentation ou évacuation : préparez votre projet d'installation plomberie à Marseille.", body: ["Une installation plomberie Marseille réussie commence par un état des lieux du réseau existant. L'accès, la pente des évacuations, la pression, le type de matériaux et la ventilation peuvent influencer le projet.", "Pour obtenir un devis utile, envoyez un plan ou des photos, précisez les équipements souhaités et indiquez si le logement est occupé. Cela permet d'anticiper les protections, les coupures et le calendrier."], questions: baseQuestions, related: ["plomberie-marseille", "plombier-marseille", "chauffe-eau-marseille"] },
];

const arrondissementNames: Record<string, string> = { "13001": "Marseille 1er", "13002": "Marseille 2e", "13003": "Marseille 3e", "13004": "Marseille 4e", "13005": "Marseille 5e", "13006": "Marseille 6e", "13007": "Marseille 7e", "13008": "Marseille 8e", "13009": "Marseille 9e", "13010": "Marseille 10e", "13011": "Marseille 11e", "13012": "Marseille 12e", "13013": "Marseille 13e", "13014": "Marseille 14e", "13015": "Marseille 15e", "13016": "Marseille 16e" };
const cityNames = ["Aubagne", "Allauch", "Plan-de-Cuques", "Cassis", "La Penne-sur-Huveaune", "Roquevaire", "Cabries", "Septèmes-les-Vallons"];

const localPages: SeoPage[] = Object.entries(arrondissementNames).map(([postal, name]) => ({ slug: `plombier-marseille-${postal}`, keyword: `plombier ${name}`, title: `Plombier ${name} : dépannage et devis local`, area: name, intro: `Vous cherchez un plombier à ${name} ? Fuite d'eau, WC bouché, chauffe-eau, canalisation ou rénovation : décrivez votre problème et votre quartier pour une orientation locale.`, body: [`La recherche plombier ${name} correspond à des situations différentes selon l'immeuble, le quartier et l'urgence. Cette page dédiée à ${name} rassemble les demandes de plomberie les plus fréquentes et les informations à préparer avant un rendez-vous.`, `Pour un plombier à ${name}, indiquez si l'eau coule encore, si le logement est en copropriété et si l'accès est simple. Ces détails permettent de préparer une intervention adaptée, sans multiplier les échanges.`], questions: baseQuestions, related: ["plombier-marseille", "urgence-plomberie-marseille", "fuite-eau-marseille"] }));
const cityPages: SeoPage[] = cityNames.map((name) => ({ slug: `plombier-${name.toLowerCase().replaceAll(" ", "-")}`, keyword: `plombier ${name}`, title: `Plombier ${name} : une demande simple et locale`, area: name, intro: `Besoin d'un plombier à ${name} ou dans les environs ? Décrivez votre urgence, votre dépannage ou votre projet de plomberie pour être orienté vers le bon interlocuteur.`, body: [`Un plombier ${name} peut être recherché pour une fuite, un débouchage, une panne de chauffe-eau ou une installation. La commune et le quartier sont les premières informations à transmettre pour vérifier la zone d'intervention.`, `Pour une demande de plombier à ${name}, préparez une description courte, des photos si possible et le niveau d'urgence. Pour un chantier, ajoutez les dimensions, les équipements souhaités et votre calendrier.`], questions: baseQuestions, related: ["plombier-marseille", "plomberie-marseille", "urgence-plomberie-marseille"] }));

export const seoPages: Record<string, SeoPage> = Object.fromEntries([...servicePages, ...localPages, ...cityPages].map((page) => [page.slug, page]));
export const seoPageList = [...servicePages, ...localPages, ...cityPages];
